import Head from 'next/head';
import Link from 'next/link';
import type { GetStaticPaths, GetStaticProps } from 'next';
import { HiArrowLeft, HiArrowUpRight, HiCheckCircle, HiClock, HiCurrencyDollar, HiExclamationTriangle, HiLanguage } from 'react-icons/hi2';
import { Layout } from '../../components/layout/Layout';
import { Arrow, cardGradients, GuideFooter } from '../../components/guide/GuideUI';
import { CountryFlag } from '../../components/guide/CountryFlag';
import { COUNTRIES, type Country } from '../../lib/global-guide';

export const getStaticPaths: GetStaticPaths = async () => ({ paths: COUNTRIES.map((country) => ({ params: { slug: country.id } })), fallback: false });
export const getStaticProps: GetStaticProps = async ({ params }) => ({ props: { country: COUNTRIES.find((item) => item.id === params?.slug) } });

export default function Destination({ country }: { country: Country }) {
  return <Layout headerTheme="light"><Head><title>{`${country.name} | Guia MoveEasy`}</title><meta name="description" content={country.introduction} /></Head><div className="guide-page">
    <section className="relative overflow-hidden text-white" style={{ background: cardGradients[country.id] }}><div className="absolute size-[550px] rounded-full border border-white/15 -right-40 -top-64 pointer-events-none" /><div className="absolute size-[380px] rounded-full border border-white/10 -right-10 -bottom-72 pointer-events-none" /><div className="guide-container py-11 sm:py-16 relative"><Link href="/destinos" className="inline-flex items-center gap-2 text-white/80 hover:text-white text-sm font-semibold"><HiArrowLeft className="size-4" /> Todos os destinos</Link><div className="mt-9 grid md:grid-cols-[1fr_auto] gap-6 items-end"><div><p className="text-white/70 uppercase tracking-[.18em] text-xs font-extrabold">Guia de destino</p><div className="flex items-center gap-5 mt-4"><CountryFlag countryId={country.id} className="w-20 sm:w-24" /><h1 className="text-4xl sm:text-6xl font-black tracking-tight">{country.name}</h1></div><p className="text-white/85 text-lg max-w-2xl mt-6 leading-relaxed">{country.introduction}</p></div><span className="rounded-full border border-white/30 bg-white/10 px-4 py-2 text-sm font-semibold inline-flex gap-2 items-center w-fit"><HiLanguage className="size-5" /> {country.language}</span></div></div></section>

    <section className="guide-container py-12 sm:py-16"><div className="grid lg:grid-cols-[1fr_320px] gap-8 items-start">
      <div>
        <p className="guide-kicker mb-4">Visão geral</p><h2 className="guide-section-title">O que considerar antes de ir</h2>
        <div className="grid sm:grid-cols-2 gap-5 mt-8"><div className="guide-panel p-6"><span className="size-11 rounded-xl bg-emerald-100 text-teal-700 flex items-center justify-center"><HiCheckCircle className="size-6" /></span><h3 className="font-extrabold text-xl mt-5">O que pode atrair</h3><ul className="space-y-3 text-slate-600 text-sm mt-4">{country.advantages.map((item) => <li className="flex gap-2" key={item}><span className="text-teal-700 font-bold">✓</span>{item}</li>)}</ul></div><div className="guide-panel p-6"><span className="size-11 rounded-xl bg-amber-100 text-amber-700 flex items-center justify-center"><HiExclamationTriangle className="size-6" /></span><h3 className="font-extrabold text-xl mt-5">O que exige atenção</h3><ul className="space-y-3 text-slate-600 text-sm mt-4">{country.challenges.map((item) => <li className="flex gap-2" key={item}><span className="text-amber-700 font-bold">!</span>{item}</li>)}</ul></div></div>
        <div className="grid sm:grid-cols-2 gap-5 mt-5"><div className="guide-panel p-6"><HiCurrencyDollar className="size-6 text-teal-700" /><h3 className="font-bold mt-4">Custos a planejar</h3><p className="text-slate-600 text-sm mt-2 leading-relaxed">{country.cost}</p></div><div className="guide-panel p-6"><HiClock className="size-6 text-teal-700" /><h3 className="font-bold mt-4">Tempo de processo</h3><p className="text-slate-600 text-sm mt-2 leading-relaxed">{country.timing}</p></div></div>
      </div>
      <aside className="guide-dark rounded-3xl p-7 lg:sticky lg:top-24"><p className="text-emerald-200 text-xs uppercase tracking-widest font-extrabold">Próximo passo</p><h2 className="text-2xl font-extrabold tracking-tight mt-4">Esse destino faz sentido para você?</h2><p className="text-emerald-100/80 text-sm leading-relaxed mt-3">Compare seus objetivos com os caminhos disponíveis em um diagnóstico gratuito.</p><Link href="/diagnostico" className="guide-cta bg-white text-slate-900 w-full mt-6">Analisar meu perfil <Arrow /></Link><p className="text-emerald-100/60 text-xs mt-5">Sem promessa de elegibilidade ou aprovação.</p></aside>
    </div></section>

    <section className="guide-soft py-16 sm:py-20" id="caminhos"><div className="guide-container"><p className="guide-kicker mb-4">Como ir</p><h2 className="guide-section-title">Caminhos para investigar</h2><p className="guide-lead max-w-3xl mt-4">Selecione o caminho ligado ao seu objetivo e consulte a autoridade responsável antes de iniciar qualquer pedido.</p><div className="grid lg:grid-cols-3 gap-5 mt-9">{country.routes.map((route, index) => <article key={route.id} id={route.id} className="guide-panel p-6 flex flex-col scroll-mt-24"><span className="text-xs font-extrabold tracking-widest text-teal-700">CAMINHO {String(index + 1).padStart(2, '0')}</span><h3 className="text-xl font-extrabold mt-3">{route.title}</h3><p className="text-slate-600 text-sm mt-3 leading-relaxed">{route.summary}</p><h4 className="font-bold text-sm mt-6">Confirme principalmente</h4><ul className="text-slate-600 text-sm list-disc pl-5 mt-2 space-y-2">{route.requirements.map((requirement) => <li key={requirement}>{requirement}</li>)}</ul><a href={route.source.url} target="_blank" rel="noopener noreferrer" className="guide-link inline-flex items-center gap-1 text-sm mt-auto pt-7">Abrir fonte oficial <HiArrowUpRight className="size-4" /><span className="sr-only">: {route.source.label}</span></a></article>)}</div></div></section>

    <div className="guide-container py-10"><p className="text-xs text-slate-500 max-w-4xl">Conteúdo revisado em {new Date(`${country.reviewedAt}T12:00:00`).toLocaleDateString('pt-BR')}. Custos, prazos e requisitos variam conforme o caso e podem mudar. Este guia é educativo e não substitui orientação profissional.</p></div><GuideFooter />
  </div></Layout>;
}
